package com.nir.trainswatch;

import java.util.HashMap;
import java.util.Set;

/**
 * Created by Nirmal on 11/8/2016.
 */

public class Data {
    protected static HashMap<String, Integer> stationIds;
    protected static String[] stationNames;

    protected static void fillStationIds() {
        stationIds = new HashMap<String, Integer>();

        stationIds.put("Abanpola", 3);
        stationIds.put("Adagala", 410);
        stationIds.put("Ahangama", 11);
        stationIds.put("Ahungalle", 18);
        stationIds.put("Akbopura", 13);
        stationIds.put("Akurala", 7);
        stationIds.put("Alawatupitiya", 22);
        stationIds.put("Alawwa", 9);
        stationIds.put("Aluth Ambalama", 329);
        stationIds.put("Aluthgama", 8);
        stationIds.put("Ambalangoda", 1);
        stationIds.put("Ambewela", 2);
        stationIds.put("Ambeypussa", 14);
        stationIds.put("Anawilundawa", 19);
        stationIds.put("Andadola", 10);
        stationIds.put("Angampitiya", 5);
        stationIds.put("Angulana", 4);
        stationIds.put("Anuradhapura", 12);
        stationIds.put("Anuradhapura Town", 15);
        stationIds.put("Arachchikattuwa", 6);
        stationIds.put("Arapathgama", 343);
        stationIds.put("Arukkuwatte", 16);
        stationIds.put("Aselapura", 17);
        stationIds.put("Asgiriya", 467);
        stationIds.put("Aukana", 21);
        stationIds.put("Avissawella", 20);
        stationIds.put("Badulla", 23);
        stationIds.put("Balana", 31);
        stationIds.put("Balapitiya", 34);
        stationIds.put("Bambalapitiya", 35);
        stationIds.put("Bandarawela", 25);
        stationIds.put("Bandirippuwa", 475);
        stationIds.put("Bangadeniya", 28);
        stationIds.put("Baseline Road", 39);
        stationIds.put("Battaluoya", 33);
        stationIds.put("Batticaloa", 24);
        stationIds.put("Batuwatte", 41);
        stationIds.put("Bemmulla", 26);
        stationIds.put("Bentota", 32);
        stationIds.put("Beruwala", 36);
        stationIds.put("Bolawatte", 30);
        stationIds.put("Boossa", 38);
        stationIds.put("Borelessa", 37);
        stationIds.put("Botale", 40);
        stationIds.put("Bulugahagoda", 27);
        stationIds.put("Buthgamuwa", 29);
        stationIds.put("Chavakachcheri", 398);
        stationIds.put("Cheddiikulam", 371);
        stationIds.put("Chilaw", 44);
        stationIds.put("China Bey", 43);
        stationIds.put("Chunnakam", 423);
        stationIds.put("Colombo Fort", 61);
        stationIds.put("Cotta Road", 46);
        stationIds.put("Daraluwa", 53);
        stationIds.put("Dec", 457);
        stationIds.put("Dehiwala", 54);
        stationIds.put("Dekinda", 337);
        stationIds.put("Dematagoda", 47);
        stationIds.put("Demodara", 48);
        stationIds.put("Dewapuram", 52);
        stationIds.put("Dewedda", 417);
        stationIds.put("Diyatalawa", 50);
        stationIds.put("Dodanduwa", 51);
        stationIds.put("Egoda Uyana", 60);
        stationIds.put("Eliphant Pass", 395);
        stationIds.put("Elle", 57);
        stationIds.put("Eluthumattuval", 401);
        stationIds.put("Elwala", 341);
        stationIds.put("Enderamulla", 55);
        stationIds.put("Erattaperiyakulam", 56);
        stationIds.put("Eravur", 59);
        stationIds.put("Erukkalam Pendu", 58);
        stationIds.put("Free Trade Zone", 104);
        stationIds.put("Galaboda", 64);
        stationIds.put("Galgamuwa", 69);
        stationIds.put("Galle", 68);
        stationIds.put("Gallella", 62);
        stationIds.put("Galoya Junction", 74);
        stationIds.put("Gammana", 70);
        stationIds.put("Gampaha", 75);
        stationIds.put("Gampola", 76);
        stationIds.put("Ganegoda", 71);
        stationIds.put("Ganemulla", 63);
        stationIds.put("Ganewatte", 73);
        stationIds.put("Gangoda", 65);
        stationIds.put("Gantalawa", 440);
        stationIds.put("Gelioya", 66);
        stationIds.put("Ginthota", 72);
        stationIds.put("Girambe", 77);
        stationIds.put("Godagama", 67);
        stationIds.put("Great Western", 79);
        stationIds.put("Habaraduwa", 81);
        stationIds.put("Habarana", 82);
        stationIds.put("Hadiriwalana", 456);
        stationIds.put("Haliela", 84);
        stationIds.put("Haputale", 92);
        stationIds.put("Hatamuna", 80);
        stationIds.put("Hataras Kotuwa", 87);
        stationIds.put("Hatton", 96);
        stationIds.put("Heel Oya", 89);
        stationIds.put("Heendeniya", 83);
        stationIds.put("Hettimulla", 91);
        stationIds.put("Hikkaduwa", 86);
        stationIds.put("Hingurakgoda", 93);
        stationIds.put("Hingurala", 444);
        stationIds.put("Hiriyala", 94);
        stationIds.put("Homagama", 90);
        stationIds.put("Homagama Hospital", 85);
        stationIds.put("Horape", 95);
        stationIds.put("Horiwiala", 88);
        stationIds.put("Hunupitiya", 97);
        stationIds.put("Hyinport", 98);
        stationIds.put("Idalgasinna", 100);
        stationIds.put("Ihalagama", 101);
        stationIds.put("Ihalakotte", 102);
        stationIds.put("Ihalawatawala", 105);
        stationIds.put("Induruwa", 99);
        stationIds.put("Inguruoya", 103);
        stationIds.put("Inuvil", 428);
        stationIds.put("Ja-ela", 107);
        stationIds.put("Jaffna", 400);
        stationIds.put("Jayanthipura", 106);
        stationIds.put("Kachcheri Hall", 338);
        stationIds.put("Kadadasi Nagar", 114);
        stationIds.put("Kadigamuwa", 128);
        stationIds.put("Kadugannawa", 120);
        stationIds.put("Kadugoda", 113);
        stationIds.put("Kahawa", 152);
        stationIds.put("Kakkapalliya", 154);
        stationIds.put("Kalawewa", 127);
        stationIds.put("Kalkudah", 123);
        stationIds.put("Kalutara North", 147);
        stationIds.put("Kalutara South", 148);
        stationIds.put("Kamburugamuwa", 130);
        stationIds.put("Kandana", 108);
        stationIds.put("Kandegoda", 119);
        stationIds.put("Kandy", 115);
        stationIds.put("Kankesanthurai", 424);
        stationIds.put("Kantale", 132);
        stationIds.put("Kapuwatte", 110);
        stationIds.put("Karadipuwal", 139);
        stationIds.put("Kathaluwa", 146);
        stationIds.put("Kattuwa", 109);
        stationIds.put("Katugastota", 144);
        stationIds.put("Katugastota     Road", 468);
        stationIds.put("Katugoda", 150);
        stationIds.put("Katukurunda", 122);
        stationIds.put("Katunayaka Airport", 42);
        stationIds.put("Katunayake", 145);
        stationIds.put("Keenawala", 117);
        stationIds.put("Kekirawa", 141);
        stationIds.put("Kelaniya", 124);
        stationIds.put("Kilinochchi", 333);
        stationIds.put("Kinigama", 133);
        stationIds.put("Kirindiwela", 447);
        stationIds.put("Kirulapana", 138);
        stationIds.put("Kital Elle", 116);
        stationIds.put("Kochchikade", 111);
        stationIds.put("Kodikamam", 397);
        stationIds.put("Koggala", 134);
        stationIds.put("Kohombiliwala", 474);
        stationIds.put("Kokuvil", 429);
        stationIds.put("Kollupitiya", 126);
        stationIds.put("Kolonnawa", 125);
        stationIds.put("Kolonnawa", 453);
        stationIds.put("Kompannavediya", 140);
        stationIds.put("Kondavil", 422);
        stationIds.put("Konwewa", 135);
        stationIds.put("Koralawella", 136);
        stationIds.put("Kosgama", 143);
        stationIds.put("Kosgoda", 112);
        stationIds.put("Koshinna", 121);
        stationIds.put("Kotagala", 118);
        stationIds.put("Kottawa", 137);
        stationIds.put("Kuda Wawa", 153);
        stationIds.put("Kudahakapola", 149);
        stationIds.put("Kumarakanda", 131);
        stationIds.put("Kumbalgama", 129);
        stationIds.put("Kurahanhenagama", 408);
        stationIds.put("Kurana", 151);
        stationIds.put("Kurunegala", 142);
        stationIds.put("Laksauyana", 158);
        stationIds.put("Liyanagemulla", 155);
        stationIds.put("Liyanwala", 334);
        stationIds.put("Lunawa", 156);
        stationIds.put("Lunuwila", 157);
        stationIds.put("Madampagama", 181);
        stationIds.put("Madampe", 161);
        stationIds.put("Madhu Road", 372);
        stationIds.put("Madurankuliya", 174);
        stationIds.put("Magalegoda", 393);
        stationIds.put("Magalegoda", 472);
        stationIds.put("Maggona", 167);
        stationIds.put("Magulegoda", 452);
        stationIds.put("Mahaiyawa", 190);
        stationIds.put("Maharagama", 159);
        stationIds.put("Maho", 170);
        stationIds.put("Malapalle", 182);
        stationIds.put("Mallakam", 427);
        stationIds.put("Manampitiya", 183);
        stationIds.put("Mangalaeliya", 165);
        stationIds.put("Mankulam", 331);
        stationIds.put("Mannar", 434);
        stationIds.put("Manuwangama", 179);
        stationIds.put("Maradana", 160);
        stationIds.put("Marakona", 462);
        stationIds.put("Maraluwewa", 454);
        stationIds.put("Matale", 186);
        stationIds.put("Matara", 187);
        stationIds.put("Mathottam", 432);
        stationIds.put("Mavilmada", 466);
        stationIds.put("Mavittapuram", 425);
        stationIds.put("Medagama", 163);
        stationIds.put("Medawachchiya", 189);
        stationIds.put("Meddegama", 421);
        stationIds.put("Meegammana", 464);
        stationIds.put("Meegoda", 164);
        stationIds.put("Meesalai", 403);
        stationIds.put("Mha Induruwa", 188);
        stationIds.put("Midigama", 162);
        stationIds.put("Mihintale", 169);
        stationIds.put("Mihintale Junction", 168);
        stationIds.put("Minneriya", 173);
        stationIds.put("Mirigama", 171);
        stationIds.put("Mirihanpitigama", 409);
        stationIds.put("Mirissa", 172);
        stationIds.put("Miriswatta", 443);
        stationIds.put("Mirusuvil", 402);
        stationIds.put("Mollipatana", 177);
        stationIds.put("Moragollagama", 176);
        stationIds.put("Morakele", 175);
        stationIds.put("Moratuwa", 184);
        stationIds.put("Mount Lavinia", 439);
        stationIds.put("Mundal", 180);
        stationIds.put("Murikandy", 332);
        stationIds.put("Murunkan", 431);
        stationIds.put("Muththettugala", 185);
        stationIds.put("Nagollagama", 191);
        stationIds.put("Nailiya", 196);
        stationIds.put("Nanuoya", 197);
        stationIds.put("Narahenpita", 195);
        stationIds.put("Nattandiya", 192);
        stationIds.put("Navatkuli", 399);
        stationIds.put("Nawalapitiya", 201);
        stationIds.put("Nawinna", 202);
        stationIds.put("Negama", 194);
        stationIds.put("Negombo", 193);
        stationIds.put("Nelumpathgama", 415);
        stationIds.put("Nelumpokuna", 199);
        stationIds.put("Neriyakulam", 370);
        stationIds.put("Nooranagar", 198);
        stationIds.put("Nugegoda", 200);
        stationIds.put("Ohiya", 203);
        stationIds.put("Omanthai", 204);
        stationIds.put("Padukka", 208);
        stationIds.put("Pahalawardhana", 420);
        stationIds.put("Palavi", 238);
        stationIds.put("Pallai", 396);
        stationIds.put("Palle Talavinna", 465);
        stationIds.put("Pallewala", 219);
        stationIds.put("Palugaswewa", 237);
        stationIds.put("Panadura", 223);
        stationIds.put("Panagoda", 224);
        stationIds.put("Panaleeya", 226);
        stationIds.put("Pangiriwatta", 233);
        stationIds.put("Pannipitiya", 205);
        stationIds.put("Parakumpura", 216);
        stationIds.put("Paranthan", 394);
        stationIds.put("Parasangahawewa", 213);
        stationIds.put("Patagamgoda", 209);
        stationIds.put("Pathanpha", 236);
        stationIds.put("Pattipola", 230);
        stationIds.put("Payagala North", 211);
        stationIds.put("Payagala South", 212);
        stationIds.put("Pemrose", 232);
        stationIds.put("Peradeniya", 207);
        stationIds.put("Perakumpura", 459);
        stationIds.put("Peralanda", 231);
        stationIds.put("Periyanagavillu", 227);
        stationIds.put("Pesalai", 436);
        stationIds.put("Piliduwa", 217);
        stationIds.put("Pilimatalawa", 222);
        stationIds.put("Pinnagolla", 416);
        stationIds.put("Pinnawala", 228);
        stationIds.put("Pinwatte", 214);
        stationIds.put("Piyadigama", 210);
        stationIds.put("Piyagama", 240);
        stationIds.put("Polgahawela", 218);
        stationIds.put("Polonnaruwa", 220);
        stationIds.put("Polwathumodara", 221);
        stationIds.put("Poonewa", 229);
        stationIds.put("Porapola", 419);
        stationIds.put("Porapola Junc.", 418);
        stationIds.put("Potuhera", 234);
        stationIds.put("Pulachchikulam", 206);
        stationIds.put("Puliyankulam", 330);
        stationIds.put("Punani", 225);
        stationIds.put("Punkankulam", 406);
        stationIds.put("Puttalam", 235);
        stationIds.put("Puwakpitiya", 445);
        stationIds.put("Puwakpitiya Town", 446);
        stationIds.put("Radella", 243);
        stationIds.put("Ragama", 246);
        stationIds.put("Rambukkana", 241);
        stationIds.put("Ranamuggamuwa", 247);
        stationIds.put("Randenigama", 245);
        stationIds.put("Rathgama", 249);
        stationIds.put("Ratmalana", 248);
        stationIds.put("Redeethenna", 244);
        stationIds.put("Richmond Hill", 242);
        stationIds.put("Rosella", 250);
        stationIds.put("Saliyapura", 251);
        stationIds.put("Sankathanai", 404);
        stationIds.put("Sarasaviuyana", 257);
        stationIds.put("Sawarana", 259);
        stationIds.put("Secretartat Halt", 252);
        stationIds.put("Seeduwa", 253);
        stationIds.put("Seenigama", 255);
        stationIds.put("Senarathgama", 254);
        stationIds.put("Sevanapitiya", 258);
        stationIds.put("Siyabalangamuwa", 339);
        stationIds.put("Siyalangamuwa", 260);
        stationIds.put("Srawasthipura", 256);
        stationIds.put("Talaimannar", 437);
        stationIds.put("Talaimannar Pier", 438);
        stationIds.put("Talawa", 270);
        stationIds.put("Talawakele", 269);
        stationIds.put("Talawattegedara", 276);
        stationIds.put("Tawalanoya", 461);
        stationIds.put("Tellipallai", 426);
        stationIds.put("Telwatte", 277);
        stationIds.put("Tembligala", 262);
        stationIds.put("Thachanthoppu", 405);
        stationIds.put("Thalpe", 271);
        stationIds.put("Thambagalla", 414);
        stationIds.put("Thambuttegama", 263);
        stationIds.put("Thampalakamam", 450);
        stationIds.put("Thandikulam", 265);
        stationIds.put("Thiiruketheeswaram", 433);
        stationIds.put("Thilladiya", 267);
        stationIds.put("Thiranagama", 272);
        stationIds.put("Thoddaveli", 435);
        stationIds.put("Thuruliyagama", 455);
        stationIds.put("Timbiriyagedara", 268);
        stationIds.put("Tismalpola", 274);
        stationIds.put("Train Halt 01", 273);
        stationIds.put("Trincomalee", 264);
        stationIds.put("Tudella", 275);
        stationIds.put("Tummodara", 266);
        stationIds.put("Udatalawinna", 278);
        stationIds.put("Udaththawala", 285);
        stationIds.put("Udhamulla", 281);
        stationIds.put("Udugodagama", 413);
        stationIds.put("Uduwara", 279);
        stationIds.put("Uggalla", 280);
        stationIds.put("Ukuwela", 282);
        stationIds.put("Ulapane", 283);
        stationIds.put("Unawatuna", 284);
        stationIds.put("Urugodawattha", 451);
        stationIds.put("Uyangalla", 412);
        stationIds.put("Valachchenei", 286);
        stationIds.put("Vandaramullai", 288);
        stationIds.put("Vavuniya", 289);
        stationIds.put("Veyangoda", 287);
        stationIds.put("Viralmurippuwa", 340);
        stationIds.put("Wadduwa", 292);
        stationIds.put("Waga", 295);
        stationIds.put("Waikkala", 299);
        stationIds.put("Walahapitiya", 296);
        stationIds.put("Walaswewa", 407);
        stationIds.put("Walgama", 301);
        stationIds.put("Walpola", 303);
        stationIds.put("Wanawasala", 306);
        stationIds.put("Wandurawa", 305);
        stationIds.put("Watagoda", 308);
        stationIds.put("Wataraka", 336);
        stationIds.put("Watawala", 300);
        stationIds.put("Wattegama", 294);
        stationIds.put("Weligama", 302);
        stationIds.put("Welikanda", 298);
        stationIds.put("Wellawa", 293);
        stationIds.put("Wellawatta", 307);
        stationIds.put("Weragala", 411);
        stationIds.put("Wijayarajadahana", 304);
        stationIds.put("Wilwatte", 309);
        stationIds.put("Wlakubura", 297);
        stationIds.put("Yagoda", 473);
        stationIds.put("Yagoda", 387);
        stationIds.put("Yapahuwa", 315);
        stationIds.put("Yatagama", 313);
        stationIds.put("Yatawara", 463);
        stationIds.put("Yatirawana", 311);
        stationIds.put("Yattalgoda", 316);

        Set<String> keys = stationIds.keySet();
        stationNames = keys.toArray(new String[keys.size()]);
    }
}
