package com.nir.trainswatch;

import android.widget.Toast;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;

/**
 * Created by Nirmal on 11/9/2016.
 */

public class MalindaAdapter extends WebServiceAdapter {

    private static HashMap<String, String> stationIds;
    private static void fillStationIds() {
        stationIds = new HashMap<String, String>();

        stationIds.put("Abanpola", "ABN");
        stationIds.put("Adagala", "ADAGALA");
        stationIds.put("Ahangama", "ANM");
        stationIds.put("Ahungalle", "AUH");
        stationIds.put("Akbopura", "APR");
        stationIds.put("Akurala", "AKU");
        stationIds.put("Alawatupitiya", "AWP");
        stationIds.put("Alawwa", "ALW");
        stationIds.put("Aluth Ambalama", "ATB");
        stationIds.put("Aluthgama", "ALT");
        stationIds.put("Ambalangoda", "ABA");
        stationIds.put("Ambewela", "ABL");
        stationIds.put("Ambeypussa", "APS");
        stationIds.put("Anawilundawa", "AVD");
        stationIds.put("Andadola", "AND");
        stationIds.put("Angampitiya", "AGT");
        stationIds.put("Angulana", "AGL");
        stationIds.put("Anuradhapura", "ANP");
        stationIds.put("Anuradhapura Town", "APT");
        stationIds.put("Arachchikattuwa", "AKT");
        stationIds.put("Arapathgama", "Arapangama");
        stationIds.put("Arukkuwatte", "ARW");
        stationIds.put("Aselapura", "ASL");
        stationIds.put("Aukana", "AWK");
        stationIds.put("Avissawella", "AVS");
        stationIds.put("Badulla", "BAD");
        stationIds.put("Balana", "BNA");
        stationIds.put("Balapitiya", "BPA");
        stationIds.put("Bambalapitiya", "BPT");
        stationIds.put("Bandarawela", "BDA");
        stationIds.put("Bangadeniya", "BGY");
        stationIds.put("Baseline Road", "BSL");
        stationIds.put("Battaluoya", "BOA");
        stationIds.put("Batticaloa", "BCO");
        stationIds.put("Batuwatte", "BTU");
        stationIds.put("Bemmulla", "BEM");
        stationIds.put("Bentota", "BNT");
        stationIds.put("Beruwala", "BRL");
        stationIds.put("Bolawatte", "BLT");
        stationIds.put("Boossa", "BSH");
        stationIds.put("Borelessa", "BSA");
        stationIds.put("Botale", "BTL");
        stationIds.put("Bulugahagoda", "BGH");
        stationIds.put("Buthgamuwa", "BJM");
        stationIds.put("Chavakachcheri", "CCH");
        stationIds.put("Cheddiikulam", "CDK");
        stationIds.put("Chilaw", "CHL");
        stationIds.put("China Bey", "CBY");
        stationIds.put("Colombo Fort", "FOT");
        stationIds.put("Cotta Road", "CRD");
        stationIds.put("Daraluwa", "DRL");
        stationIds.put("Dehiwala", "DWL");
        stationIds.put("Dekinda", "DKD");
        stationIds.put("Dematagoda", "DAG");
        stationIds.put("Demodara", "DDR");
        stationIds.put("Dewapuram", "DPM");
        stationIds.put("Dewedda", "DEWEDDA");
        stationIds.put("Diyatalawa", "DLA");
        stationIds.put("Dodanduwa", "DNA");
        stationIds.put("Egoda Uyana", "EYA");
        stationIds.put("Eliphant Pass", "EPS");
        stationIds.put("Elle", "ELL");
        stationIds.put("Eluthumattuval", "EML");
        stationIds.put("Elwala", "Elwala");
        stationIds.put("Enderamulla", "EDM");
        stationIds.put("Erattaperiyakulam", "EKM");
        stationIds.put("Eravur", "EVR");
        stationIds.put("Erukkalam Pendu", "EPN");
        stationIds.put("Free Trade Zone", "IPZ");
        stationIds.put("Galaboda", "GBD");
        stationIds.put("Galgamuwa", "GLM");
        stationIds.put("Galle", "GLE");
        stationIds.put("Gallella", "GAL");
        stationIds.put("Galoya Junction", "GOA");
        stationIds.put("Gammana", "GMA");
        stationIds.put("Gampaha", "GPH");
        stationIds.put("Gampola", "GPL");
        stationIds.put("Ganegoda", "GND");
        stationIds.put("Ganemulla", "GAN");
        stationIds.put("Ganewatte", "GNW");
        stationIds.put("Gangoda", "GDA");
        stationIds.put("Gelioya", "GEY");
        stationIds.put("Ginthota", "GNT");
        stationIds.put("Girambe", "GRB");
        stationIds.put("Godagama", "GGA");
        stationIds.put("Great Western", "GWN");
        stationIds.put("Habaraduwa", "HBD");
        stationIds.put("Habarana", "HBN");
        stationIds.put("Haliela", "HEA");
        stationIds.put("Haputale", "HPT");
        stationIds.put("Hatamuna", "HAU");
        stationIds.put("Hataras Kotuwa", "HKT");
        stationIds.put("Hatton", "HTN");
        stationIds.put("Heel Oya", "HLO");
        stationIds.put("Heendeniya", "HDP");
        stationIds.put("Hettimulla", "HML");
        stationIds.put("Hikkaduwa", "HKD");
        stationIds.put("Hingurakgoda", "HRG");
        stationIds.put("Hiriyala", "HRL");
        stationIds.put("Homagama", "HMA");
        stationIds.put("Homagama Hospital", "HHR");
        stationIds.put("Horape", "HRP");
        stationIds.put("Horiwiala", "HLA");
        stationIds.put("Hunupitiya", "HUN");
        stationIds.put("Hyinport", "HYP");
        stationIds.put("Idalgasinna", "IGH");
        stationIds.put("Ihalagama", "IHA");
        stationIds.put("Ihalakotte", "IKT");
        stationIds.put("Ihalawatawala", "IWL");
        stationIds.put("Induruwa", "IDA");
        stationIds.put("Inguruoya", "INO");
        stationIds.put("Ja-ela", "JLA");
        stationIds.put("Jaffna", "JFN");
        stationIds.put("Jayanthipura", "JAP");
        stationIds.put("Kachcheri Hall", "Kachcheri Halt");
        stationIds.put("Kadadasi Nagar", "KDN");
        stationIds.put("Kadigamuwa", "KMA");
        stationIds.put("Kadugannawa", "KGW");
        stationIds.put("Kadugoda", "KDG");
        stationIds.put("Kahawa", "KWE");
        stationIds.put("Kakkapalliya", "KYA");
        stationIds.put("Kalawewa", "KLW");
        stationIds.put("Kalkudah", "KKH");
        stationIds.put("Kalutara North", "KTN");
        stationIds.put("Kalutara South", "KTS");
        stationIds.put("Kamburugamuwa", "KMG");
        stationIds.put("Kandana", "KAN");
        stationIds.put("Kandegoda", "KGD");
        stationIds.put("Kandy", "KDT");
        stationIds.put("Kantale", "KNI");
        stationIds.put("Kapuwatte", "KAW");
        stationIds.put("Karadipuwal", "KPL");
        stationIds.put("Kathaluwa", "KTL");
        stationIds.put("Kattuwa", "KAT");
        stationIds.put("Katugastota", "KTG");
        stationIds.put("Katugoda", "KUG");
        stationIds.put("Katukurunda", "KKD");
        stationIds.put("Katunayaka Airport", "CAK");
        stationIds.put("Katunayake", "KTK");
        stationIds.put("Keenawala", "KEN");
        stationIds.put("Kekirawa", "KRA");
        stationIds.put("Kelaniya", "KLA");
        stationIds.put("Kilinochchi", "KOC");
        stationIds.put("Kinigama", "KNM");
        stationIds.put("Kirulapana", "KPE");
        stationIds.put("Kital Elle", "KEL");
        stationIds.put("Kochchikade", "KCH");
        stationIds.put("Kodikamam", "KKM");
        stationIds.put("Koggala", "KOG");
        stationIds.put("Kollupitiya", "KLP");
        stationIds.put("Kolonnawa", "KLN");
        stationIds.put("Kompannavediya", "KPN");
        stationIds.put("Konwewa", "KON");
        stationIds.put("Koralawella", "KOR");
        stationIds.put("Kosgama", "KSG");
        stationIds.put("Kosgoda", "KDA");
        stationIds.put("Koshinna", "KHA");
        stationIds.put("Kotagala", "KGA");
        stationIds.put("Kottawa", "KOT");
        stationIds.put("Kuda Wawa", "KWW");
        stationIds.put("Kudahakapola", "KUD");
        stationIds.put("Kumarakanda", "KMK");
        stationIds.put("Kumbalgama", "KMB");
        stationIds.put("Kurahanhenagama", "KURAHANHENAGAMA");
        stationIds.put("Kurana", "KUR");
        stationIds.put("Kurunegala", "KRN");
        stationIds.put("Laksauyana", "LYA");
        stationIds.put("Liyanagemulla", "LGM");
        stationIds.put("Liyanwala", "LIYANWALA");
        stationIds.put("Lunawa", "LNA");
        stationIds.put("Lunuwila", "LWL");
        stationIds.put("Madampagama", "MPA");
        stationIds.put("Madampe", "MDP");
        stationIds.put("Madhu Road", "MRD");
        stationIds.put("Madurankuliya", "MKI");
        stationIds.put("Magalegoda", "MGG");
        stationIds.put("Maggona", "MGN");
        stationIds.put("Mahaiyawa", "MYA");
        stationIds.put("Maharagama", "MAG");
        stationIds.put("Maho", "MHO");
        stationIds.put("Malapalle", "MPL");
        stationIds.put("Manampitiya", "MPT");
        stationIds.put("Mangalaeliya", "MGE");
        stationIds.put("Mankulam", "MKM");
        stationIds.put("Manuwangama", "MNG");
        stationIds.put("Maradana", "MDA");
        stationIds.put("Matale", "MTL");
        stationIds.put("Matara", "MTR");
        stationIds.put("Medagama", "MEM");
        stationIds.put("Medawachchiya", "MWH");
        stationIds.put("Meddegama", "MEDDEGAMA");
        stationIds.put("Meegoda", "MGD");
        stationIds.put("Meesalai", "MES");
        stationIds.put("Mha Induruwa", "MWA");
        stationIds.put("Midigama", "MED");
        stationIds.put("Mihintale", "MHN");
        stationIds.put("Mihintale Junction", "MHJ");
        stationIds.put("Minneriya", "MIY");
        stationIds.put("Mirigama", "MIR");
        stationIds.put("Mirihanpitigama", "MIRIHANPITIGAMA");
        stationIds.put("Mirissa", "MIS");
        stationIds.put("Mirusuvil", "MSL");
        stationIds.put("Mollipatana", "MLP");
        stationIds.put("Moragollagama", "MLG");
        stationIds.put("Morakele", "MKP");
        stationIds.put("Moratuwa", "MRT");
        stationIds.put("Mount Lavinia", "MLV");
        stationIds.put("Mundal", "MNL");
        stationIds.put("Murikandy", "MRK");
        stationIds.put("Muththettugala", "MTG");
        stationIds.put("Nagollagama", "NAG");
        stationIds.put("Nailiya", "NLY");
        stationIds.put("Nanuoya", "NOA");
        stationIds.put("Narahenpita", "NHP");
        stationIds.put("Nattandiya", "NAT");
        stationIds.put("Navatkuli", "NVT");
        stationIds.put("Nawalapitiya", "NVP");
        stationIds.put("Nawinna", "NWN");
        stationIds.put("Negama", "NGM");
        stationIds.put("Negombo", "NGB");
        stationIds.put("Nelumpathgama", "NELUMPATHGAMA");
        stationIds.put("Nelumpokuna", "NPK");
        stationIds.put("Neriyakulam", "NYK");
        stationIds.put("Nooranagar", "NOR");
        stationIds.put("Nugegoda", "NUG");
        stationIds.put("Ohiya", "OHA");
        stationIds.put("Omanthai", "OMT");
        stationIds.put("Padukka", "PDK");
        stationIds.put("Pahalawardhana", "PAHALAWARDHANA");
        stationIds.put("Palavi", "PVI");
        stationIds.put("Pallai", "PAL");
        stationIds.put("Pallewala", "PLL");
        stationIds.put("Palugaswewa", "PUW");
        stationIds.put("Panadura", "PND");
        stationIds.put("Panagoda", "PNG");
        stationIds.put("Panaleeya", "PNL");
        stationIds.put("Pangiriwatta", "PRW");
        stationIds.put("Pannipitiya", "PAN");
        stationIds.put("Parakumpura", "PKU");
        stationIds.put("Paranthan", "PRN");
        stationIds.put("Parasangahawewa", "PHW");
        stationIds.put("Patagamgoda", "PGD");
        stationIds.put("Pathanpha", "PTP");
        stationIds.put("Pattipola", "PPL");
        stationIds.put("Payagala North", "PGN");
        stationIds.put("Payagala South", "PGS");
        stationIds.put("Pemrose", "PRP");
        stationIds.put("Peradeniya", "PDA");
        stationIds.put("Peralanda", "PRL");
        stationIds.put("Periyanagavillu", "PNV");
        stationIds.put("Piliduwa", "PLD");
        stationIds.put("Pilimatalawa", "PLT");
        stationIds.put("Pinnagolla", "PINNAGOLLA");
        stationIds.put("Pinnawala", "PNW");
        stationIds.put("Pinwatte", "PIN");
        stationIds.put("Piyadigama", "PGM");
        stationIds.put("Piyagama", "PYA");
        stationIds.put("Polgahawela", "PLG");
        stationIds.put("Polonnaruwa", "PLN");
        stationIds.put("Polwathumodara", "PLR");
        stationIds.put("Poonewa", "PON");
        stationIds.put("Porapola", "PORAPOLA");
        stationIds.put("Porapola Junc.", "PORAPOLA JUNC.");
        stationIds.put("Potuhera", "PTA");
        stationIds.put("Pulachchikulam", "PCK");
        stationIds.put("Puliyankulam", "PKM");
        stationIds.put("Punani", "PNI");
        stationIds.put("Punkankulam", "PNK");
        stationIds.put("Puttalam", "PTM");
        stationIds.put("Puwakpitiya", "PWP");
        stationIds.put("Radella", "RDL");
        stationIds.put("Ragama", "RGM");
        stationIds.put("Rambukkana", "RBK");
        stationIds.put("Ranamuggamuwa", "RMA");
        stationIds.put("Randenigama", "RGA");
        stationIds.put("Rathgama", "RTG");
        stationIds.put("Ratmalana", "RML");
        stationIds.put("Redeethenna", "RDL");
        stationIds.put("Richmond Hill", "RCH");
        stationIds.put("Rosella", "RZL");
        stationIds.put("Saliyapura", "SAL");
        stationIds.put("Sankathanai", "SAK");
        stationIds.put("Sarasaviuyana", "SUA");
        stationIds.put("Sawarana", "SWR");
        stationIds.put("Secretartat Halt", "SCR");
        stationIds.put("Seeduwa", "SED");
        stationIds.put("Seenigama", "SMA");
        stationIds.put("Senarathgama", "SGM");
        stationIds.put("Sevanapitiya", "SVP");
        stationIds.put("Siyabalangamuwa", "Siyabalagawewa");
        stationIds.put("Siyalangamuwa", "SYA");
        stationIds.put("Srawasthipura", "SRP");
        stationIds.put("Talawa", "TLA");
        stationIds.put("Talawakele", "TKL");
        stationIds.put("Talawattegedara", "TWG");
        stationIds.put("Telwatte", "TWT");
        stationIds.put("Tembligala", "TBL");
        stationIds.put("Thachanthoppu", "TPH");
        stationIds.put("Thalpe", "TLP");
        stationIds.put("Thambagalla", "THAMBAGALLA");
        stationIds.put("Thambuttegama", "TBM");
        stationIds.put("Thandikulam", "TDK");
        stationIds.put("Thilladiya", "TDY");
        stationIds.put("Thiranagama", "TNA");
        stationIds.put("Timbiriyagedara", "TIM");
        stationIds.put("Tismalpola", "TSM");
        stationIds.put("Train Halt 01", "TRH");
        stationIds.put("Trincomalee", "TCO");
        stationIds.put("Tudella", "TUD");
        stationIds.put("Tummodara", "TDR");
        stationIds.put("Udatalawinna", "UDL");
        stationIds.put("Udaththawala", "UWL");
        stationIds.put("Udhamulla", "UHM");
        stationIds.put("Udugodagama", "UDUGODAGAMA");
        stationIds.put("Uduwara", "UDW");
        stationIds.put("Uggalla", "UGL");
        stationIds.put("Ukuwela", "UKL");
        stationIds.put("Ulapane", "ULP");
        stationIds.put("Unawatuna", "UNW");
        stationIds.put("Uyangalla", "UYANGALLA");
        stationIds.put("Valachchenei", "VCH");
        stationIds.put("Vandaramullai", "VML");
        stationIds.put("Vavuniya", "VNA");
        stationIds.put("Veyangoda", "VGD");
        stationIds.put("Viralmurippuwa", "VIRALMURIPPUWA");
        stationIds.put("Wadduwa", "WDA");
        stationIds.put("Waga", "WGG");
        stationIds.put("Waikkala", "WKL");
        stationIds.put("Walahapitiya", "WHP");
        stationIds.put("Walaswewa", "WALASWEWA");
        stationIds.put("Walgama", "WLG");
        stationIds.put("Walpola", "WPA");
        stationIds.put("Wanawasala", "WSL");
        stationIds.put("Wandurawa", "WRW");
        stationIds.put("Watagoda", "WTG");
        stationIds.put("Wataraka", "WAP");
        stationIds.put("Watawala", "WLA");
        stationIds.put("Wattegama", "WGA");
        stationIds.put("Weligama", "WLM");
        stationIds.put("Welikanda", "WKD");
        stationIds.put("Wellawa", "WEL");
        stationIds.put("Wellawatta", "WTE");
        stationIds.put("Weragala", "WERAGALA");
        stationIds.put("Wijayarajadahana", "WRD");
        stationIds.put("Wilwatte", "WWT");
        stationIds.put("Wlakubura", "WKA");
        stationIds.put("Yagoda", "YGD");
        stationIds.put("Yapahuwa", "YPW");
        stationIds.put("Yatagama", "YGM");
        stationIds.put("Yatirawana", "YATIRAWANA");
        stationIds.put("Yattalgoda", "YTG");
    }

    public MalindaAdapter(String start, String end) {
        super(start, end);
        if (stationIds==null) fillStationIds();
        String startKey = stationIds.get(start);
        String endKey = stationIds.get(end);
        if (startKey!=null && endKey!=null) {
            // TODO: replace with todays date
            // TODO: replace with selected date
            this.url = "http://slr.malindaprasad.com/?from="+startKey+"&to="+endKey+"&date="+("2016-11-10")+"&singlebutton=";
//            Toast.makeText(SearchActivity.context, startKey+" "+endKey, Toast.LENGTH_SHORT).show();
        } else {
            Toast.makeText(SearchActivity.context, "Station name not available.", Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    public ArrayList<Train> getResults() {
        Document doc = null;
        try {
            doc = Jsoup.connect(url).get();
            Elements tables = doc.select("div.panel-body table.table-striped tbody");
            trains = new ArrayList<Train>();
            if (tables!=null && tables.size()>0) {
                for (int i=0; i<tables.size(); i++) {
                    // TODO: check structure
                    // TODO: maybe pass exception if structure fails
//                    Elements one = rows.get(i).select("td:not(td:contains(Arrival))");
//                    if (one.size()<8) {
//                        continue;
//                    }
                    Elements rows = tables.get(i).select("tr");
                    Train train = new Train();
                    train.endTime = rows.get(1).select("td:not(td:contains(Arrival))").html();
                    train.arrivalTime = rows.get(2).select("td:not(td:contains(Departure))").html();
                    train.endTime = rows.get(4).select("td:not(td:contains(Arrival))").html();
                    train.type = rows.get(5).select("td:not(td:contains(Train))").html();
                    train.name = rows.get(6).select("td:not(td:contains(Train))").html();
                    train.number = Integer.parseInt(rows.get(7).select("td:not(td:contains(Train))").html());
                    train.frequency = rows.get(9).select("td:not(td:contains(Run))").html();
                    // TODO: get class list
                    String directOrNot = rows.get(11).select("td:not(td:contains(Direct))").html();
                    train.directTrain = (directOrNot.equals("YES"))?true:false;
                    // TODO: get other data too (?? what other data)
                    trains.add(train);
                }
            } else {
                trains = null;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return trains;
    }
}
